### ISSUE TITLE
implement cluster-robust SEs

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/estimatr#1]
It would be great if `lm_robust` could please implement the SEs described in this document: https://github.com/acoppock/Green-Lab-SOP.

Right now, the `BMlmSE` function described there is pretty slow, but I bet that we could Rcpp it up real nice!

**Comment by acoppock** [comment]
Slightly more detail on this:

The `BMlmSE` function is apparently slow mostly because of the need to calculate the effective degrees of freedom.  we *only* need dfs for the construction of valid confidence intervals.  

I'm expecting that soon, the `ri2` package will depend on `estimatr`.  When doing permutation inference, there's no need to calculate confidence intervals, but I will need to calculate SEs. So it would be great if `lm_robust` could have a `ci = TRUE` default, but a `ci = FALSE` option.

**Comment by lukesonnet** [comment]
I've created a new branch for this feature, [luke-crse](https://github.com/DeclareDesign/estimatr/tree/luke-crse). I've implemented clustered standard error with an option `cluster` which takes an unquoted name of the clustered variable. The output matches output from the `BMlmSE` function and the entire thing is implemented in the Rcpp helper function, although it is somewhat of a transliteration for now.

FYI for a simple example where N = 10,000 and there are 1,000 clusters, BMlmSE takes ~2 seconds while lm_robust_se takes ~1.6 seconds. Not much of an improvement, but profiling Rcpp code is somewhat difficult.

A couple of points I could use immediate feedback on:

- Are we happy with the cluster variable being passed as a unquoted column name?
- Similarly, should I error/warn/ignore when someone says `cluster = x3, se_type = 'HC2'`? I currently ignore the `se_type` argument whenever cluster is set by the user. I'm also assuming that if we have different clustered standard errors in the future we will want them to set that using se_type and then we can set up better error handling.
- When I add tests, should I use the results from BMlmSE as a benchmark to ensure equality?
- Should I add more preprocessing (e.g. checking for any missingness in cluster var that shouldn't be there, fail if weighted and clustered for now)?

A check list for me before I submit a pull request:

- [ ] Add tests
- [ ] Check for speed gains/set up Rcpp profiling on my Windows machine
- [ ] Comment more thoroughly/check for style
- [ ] add `ci = F` flag

**Comment by graemeblair** [comment]
Thanks, Luke, this is awesome.

> Are we happy with the cluster variable being passed as a unquoted column name?

Yes? Let us know if you were thinking of something else.

> Similarly, should I error/warn/ignore when someone says cluster = x3, se_type = 'HC2'? I currently ignore the se_type argument whenever cluster is set by the user. I'm also assuming that if we have different clustered standard errors in the future we will want them to set that using se_type and then we can set up better error handling.

Good error handling sounds good. Why don't you error if they send both cluster and an se-type for now and we can change later as you suggest?

> When I add tests, should I use the results from BMlmSE as a benchmark to ensure equality?

Yes, that seems important. 

> Should I add more preprocessing (e.g. checking for any missingness in cluster var that shouldn't be there, fail if weighted and clustered for now)?

Can you think broadly about those questions for lm_cluster_se and propose any changes that make sense? We should consistently do or not do those checks whether it's clustered or not.

I've only skimmed the code in the Green et al. SOP, so perhaps you can see why this would be very difficult, but could we implement weighting now? I'm sure that will be the first request that comes in from a user for this.

Have you seen this re C++ profiling in R?
https://stackoverflow.com/questions/40343773/profiling-c-code-r

**Comment by lukesonnet** [comment]
> Good error handling sounds good. Why don't you error if they send both cluster and an se-type for now and we can change later as you suggest?

Will implement.

> > When I add tests, should I use the results from BMlmSE as a benchmark to ensure equality?

> Yes, that seems important.

I only asked in case there was a preferred benchmark. This will also mean adding the code to our tests folder, but I don't see a better solution right now. A possibility would be to use clubSandwich if it was equivalent and then it would be a `Suggests;` dependency.

> Can you think broadly about those questions for lm_cluster_se and propose any changes that make sense? We should consistently do or not do those checks whether it's clustered or not.

Yes, I'll propose a new issue to deal with data pre-processing.

> I've only skimmed the code in the Green et al. SOP, so perhaps you can see why this would be very difficult, but could we implement weighting now? I'm sure that will be the first request that comes in from a user for this.

Written in the SOP is a kick to https://github.com/jepusto/clubSandwich. That is implemented in R, and so I can cannibalize it with appropriate credit into Rcpp, but I'll open a new issue for that.

>Have you seen this re C++ profiling in R? https://stackoverflow.com/questions/40343773/profiling-c-code-r

Yes, it's just a bit trickier in Windows. I'll get it working, no worries.

**Comment by graemeblair** [comment]
Can you rename the option to cluster_variable_name to be consistent with the options in difference_in_means (which uses block_variable_name)?

Also, when I tested it it looks like it can only take factors, but only did a limited test. If that is true, can you allow the cluster variable to be character, numeric, or factor?

**Comment by lukesonnet** [comment]
Yes on both. I was trying to just match the weights but this makes sense
too.

Luke Sonnet
PhD Student, Political Science
UCLA

**Comment by lukesonnet** [comment]
Now works with numeric, character, or factor. I just wrapped it in as.factor because CPP is strongly typed its best to pass it something it can anticipate. . This is <1 millisecond for variables that are already factors and around 7 milliseconds for a variable of length 100k with 1000 clusters. I could push this task to cpp but it wouldn't be worth it.

**Comment by lukesonnet** [comment]
Currently the default for se_type is HC2. If we wanted to error when people specify se_type as anything other than "BM" when passing cluster, then we need to change the default to NULL, and then just set defaults at the top of the fn. Ie if se_type is null and no cluster -> se_type = 'HC2' else if se_type is null and cluster -> se_type = 'BM'

I'm going to implement it this way.

**Comment by lukesonnet** [comment]
Couple of comments about `ci=TRUE`. This also means pvalues won't be returned. Don't know if we should rename the argument something else. Also, I return the same exact item as before but with NAs in the pval, ci_lower, and ci_upper columns.

**Comment by acoppock** [comment]
Understood.  Let's leave it ci until a better option comes along?

**Comment by lukesonnet** [comment]
We will default to BM standard errors, which are analogous to HC2, with CIs using the BM DoF correction (without the additional IK adjustment!). People can also choose Stata which gives them the stata finite sample correction (n-1)/(n-k) * (S/(S-1)) to Vcov and returns those standard errors, and constructs CIs using S-1 as the DoF as Stata does, where S is the number of groups.

The IK paper describes everything pretty clearly [(see IK paper here)](https://www.princeton.edu/~mkolesar/papers/small-robust.pdf). Look for V_LZ2 on page 20 which is the BM ses. On the same page is the DoF correction as we currently implement it. 

I will implement the SEs as defined as V_Stata on page 19 (you can also see it on page 20 of chapter 20 of the Stata manual [here](http://www.stata.com/manuals13/u20.pdf). The only place where I can find verification that stata actually uses S-1 as the DoF for confidence intervals [is here](http://www.stata.com/support/faqs/statistics/robust-standard-errors/) and in the fact that IK benchmark their tests against this DoF in addition to the BM DoF.

The only remaining question is, do we do the IK DoF instead of the BM as I proposed above?

**Comment by lukesonnet** [comment]
I'm getting NaNs or numbers like 5e109 being returned only for the Stata SEs on i386 (32 bit) architecture, otherwise this is implemented.

I have no idea why this is happening given everything works on x64 and the BM SEs work on 32 bit architecture. I've been struggling with it for a long time. It's clearly something in the Rcpp code for the stata SEs that the 32bit compiler doesn't like. I'm continuing to poke, but any tips would be helpful.

**Comment by lukesonnet** [comment]
Solved.

How to save hours of time? init all objects in cpp with 0.0 before trying to += or else the 64bit compiler will work fine while the 32bit compiler will silently return garbage to you.

**Comment by lukesonnet** [comment]
Okay, everything here is basically finished and implemented except for the weighting (and a vignette, which Alex asked for, but I'll open a new issue for that). I'll issue a PR and if it's accepted I'll close this issue.

**Comment by lukesonnet** [comment]
Re: speed. For the BM ses, the DoF correction is the slowest part, but the SEs themselves are non-trivial, due to the need to get (I - X_s (XtX)^{-1} Xt_s)^{-1/2}. Every other setting is pretty quick.

For an example, with N=5000, intercept and one covariate, and 100 clusters we get the following times:

- `se_type = 'stata', ci  = T` : ~8.6 ms
- `se_type = 'BM', ci = F` :~46.2 ms (from profiling around 75% of this time is the above matrix square root inversion)
- `se_type = 'BM', ci = T`:  ~390 ms (huge jump resulting from getting G matrices)
- `se_type = 'BM', ci = T, coefficient_name = c('x1')` (omit DoF correction for intercept): ~350 ms

As @acoppock noted, most of the slowdown is in the DoF correction, specifically in building G. Some gains are to be had by only getting the coefficients you really need, but they aren't that substantial.

As far as I can tell, there are no nifty CPP tricks that will slim this down, I've already tried what came to mind. I think trying to figure out another way altogether to compute G that is better for Rcpp to handle, but how to do that is not obvious to me.

**Comment by lukesonnet** [comment]
PR accepted, closing issue.
