### ISSUE TITLE
Missingness in data causes many parts of lm_robust to fail

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#16]
Here is a MWE:
```
df <- data.frame(x = rnorm(100),
                 y = rnorm(100),
                 cluster = sample(1:3, size = 100, replace = T),
                 weights = runif(100))

# all work
estimatr::lm_robust(y ~ x, data = df)
estimatr::lm_robust(y ~ x, data = df, cluster_variable_name = cluster)
estimatr::lm_robust(y ~ x, data = df, weights = weights)

# add missingness, failures
df$cluster[23] <- NA
estimatr::lm_robust(y ~ x, data = df, cluster_variable_name = cluster)
df$x[23] <- NA
estimatr::lm_robust(y ~ x, data = df)
```

The problem lies in us using the original data instead of model.response to get the outcome, and in doing the same with the cluster.

**Comment by lukesonnet** [comment]
I think `model.matrix.default` calls model.frame anyways, so I'm going to go ahead and call `model.frame` first and then extract the outcome and the design_matrix.

Dealing with clusters is another thing. Should we just do listwise deletion if a cluster is missing (on top of the listwise deletion for the formula) and should we warn or just error?

**Comment by lukesonnet** [comment]
I've fixed the problem for missingness in either the outcome or the predictors and added a test. I've pushed this directly to the master branch as it is a pretty important fix.

I'll implement listwise deletion for cluster variables + a warning message that there is missingness in the clustering variable if you are okay with that.

**Comment by acoppock** [comment]
Do you mean

1) if there is missingness in the covariates (or the outcome), the
estimator drops the observation, including the relevant entry in the
cluster variable vector

or

2) if there is missingness in the cluster variable, drop the observations

or

3) both?

I think that we should do (3) with a warning if there’s missignness in the
cluster variable.

On August 17, 2017 at 3:28:09 PM, Luke Sonnet (notifications@github.com)
wrote:

I've fixed the problem for missingness in either the outcome or the
predictors and added a test. I've pushed this directly to the master branch
as it is a pretty important fix.

I'll implement listwise deletion for cluster variables + a warning message
that there is missingness in the clustering variable if you are okay with
that.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DeclareDesign/estimatr/issues/16#issuecomment-323170763>,
or mute the thread

**Comment by lukesonnet** [comment]
I'm suggesting that we do (3) with the warning for missingness in the cluster variable. So we are on the same page and I'll implement this.

**Comment by lukesonnet** [comment]
Same behavior for weights? Delete observations that have missing weights but warn if they are _only_ missing the weights variable?

**Comment by acoppock** [comment]
Yes, I think that's right

**Comment by lukesonnet** [comment]
Missingness now accommodated for outcome and covariates (list-wise deletion, no warning) and for weight and cluster variables (list-wise deletion, warning).
