### ISSUE TITLE
Default coefficient names

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#2]
Shouldn't the default be to return all coefficients rather than just "Z"?

**Comment by graemeblair** [comment]
The defaults throughout `DeclareDesign` are for a treatment variable named `Z` so that's where this came from. We were trying to make declaring a simple, two-arm trial with defaults to have as little typing as possible. But I see the value in the switch here, particularly where this package is meant to stand alone.

@acoppock thoughts?

**Comment by acoppock** [comment]
Agree with Luke re default. Let's set the default in declaredesin

**Comment by graemeblair** [comment]
Great, Luke let's return all as you suggest but have the option to subset them via that existing flag (leave it to you to set that up in the best way).
