### ISSUE TITLE
lm_robust breaks when cluster_variable_name is a character

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/estimatr#33]
... this is a problem, because `fabricatr` gives the ids as characters by default. 

```r 
rm(list = ls())
library(DeclareDesign)
library(dplyr)

population <-
  declare_population(
    cluster = level(N = 5, 
                    individuals_per_cluster = 5,
                    cluster_effect = rnorm(N)),
    individual = level(N = individuals_per_cluster,
                       noise = rnorm(N)))

potential_outcomes <- declare_potential_outcomes(
  formula = Y ~ Z + cluster_effect + noise)

assignment <- declare_assignment(clust_var = cluster, 
                                 m = 2)

estimator_factor <- declare_estimator(formula = Y ~ Z,
                               model = lm_robust,
                               cluster_variable_name = as.factor(cluster))

# Fine:
population() %>% potential_outcomes() %>% assignment() %>% reveal_outcomes() %>%  estimator_factor()

estimator_integer <- declare_estimator(formula = Y ~ Z,
                               model = lm_robust,
                               cluster_variable_name = as.integer(cluster))

# Fine:
population() %>% potential_outcomes() %>% assignment() %>% reveal_outcomes() %>%  estimator_integer()

estimator_character <- declare_estimator(formula = Y ~ Z,
                               model = lm_robust,
                               cluster_variable_name = cluster)

# Regression machine broke:
population() %>% potential_outcomes() %>% assignment() %>% reveal_outcomes() %>%  estimator_character()
```

**Comment by lukesonnet** [comment]
Thanks Jasper. I thought I had resolved this but I had not. It should all work now.

Right now it takes integer, numeric, or factor variables and works quickly with them because they are all passed as NumericVector to c++.

Because c++ is strongly typed, I have to cast character clusters as factors (which can be a slowdown for long datasets).

I think there are two solutions:
1. Warn when the cluster is a character that it's faster to pass a factor, but go ahead with the conversion
2. Build a switch in the C++ that essentially will duplicate all of the cluster code (non-trivial) and add arguments for both types of cluster, string and numeric.

**Comment by acoppock** [comment]
I think the right procedure here is to

cast characters as factors but do not warn.  Add to the documentation (in a couple of places!) that it’s faster if you pass factors.

THANKS

**Comment by lukesonnet** [comment]
ok then that is code wise and it will be mentioned in the documentation.
