### ISSUE TITLE
FR: Support quoted variable names or formulas for `clusters` and `weights`

### ISSUE THREAD

**Issue by rossellhayes** [DeclareDesign/estimatr#380]
Because functions like `lm_robust()` only support unquoted variable names for `clusters` and `weights`, it's difficult to pass arguments into them from other functions. For example:
``` r
purrr::map(
  list(am, cyl),
  ~ estimatr::lm_robust(mpg ~ hp, data = mtcars, clusters = .)
)
#> Error in purrr::map(list(am, cyl), ~estimatr::lm_robust(mpg ~ hp, data = mtcars, : object 'am' not found
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

We get an error that 'am' cannot be found because `list()` tries to evaluate its arguments before they can reach `lm_robust()`.

If `lm_robust()` could accept its arguments in a form that `list()` did not try to evaluate, like a quoted name or a formula, this would solve the problem.

**Comment by nfultz** [comment]
Because estimatr has a frankenstein of base R and rlang NSE, this is hard to get working without reading the actual code.

But this seems to work for me:

```
purrr::map2(
  list(mpg ~ hp, mpg ~ wt),
  list(quo(am), quo(cyl)),
  ~ lm_robust(.x, data = mtcars, clusters = !!.y)
)
```

Or with your new example,

```
purrr::map(
  quos(am, cyl),
  ~ estimatr::lm_robust(mpg ~ hp, data = mtcars, clusters = !!.)
)
```

`quo`/`quos` is used in the tidy-eval framework to delay the evaluation until the model frame is constructed. I would recommend updating the documentation to indicate quosures are useable, rather than changing the code to recursively evaluate formulas.

**Comment by rossellhayes** [comment]
Thanks, this is a really helpful solution!
