### ISSUE TITLE
bug in coefficient_name

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#46]
The NSE seems to be working well with cluster names and weight names, but not with coefficient. name. Is this intentional?

This works:

```
> dat <- data.frame(x = runif(10), y = runif(10))
> 
> lm_robust(y ~ x, data = dat,  coefficient_name = "x")
  coefficient_name        est        se         p  ci_lower  ci_upper df
2                x -0.2791966 0.3253278 0.4157517 -1.029404 0.4710105  8
```

But this does not:

```
> lm_robust(y ~ x, data = dat,  coefficient_name = x)
Error in lm_robust_fit(y = model_data$outcome, X = model_data$design_matrix,  : 
  object 'x' not found
```

Thanks!

**Comment by lukesonnet** [comment]
@graemeblair, this never worked (there was an commented line that appeared to fail when I inherited the code), but I think it should work. It just might be a little tricky.

@nfultz, the way this currently works is that `coefficient_name` is passed transparently through to `lm_robust_fit()`. So it is failing at that stage since it cannot find `'x'`. 

I'd rather not add it to `clean_model_data` since it doesn't really fit as a column we want to pull out of the data. And since we are now returning a list from `lm_robust()`, we store the coefficient names in that list and then subset the data frame in the S3 methods.

Because it is used in the CPP to save from unnecessary df calculations, and because it needs to be passed forward in the list, honestly the best thing to do is try to force it to be a string. Is there _any_ easy way to do this or is this verboten?

**Comment by nfultz** [comment]
I think params that end in "_name" should always be or evaluate to string
literals but I don't want to reopen yesterdays debate. Vote for not
implementing NSE -> symbol -> character conversion in this case, and it
already throws an error, albeit not the most helpful one.

**Comment by lukesonnet** [comment]
@graemeblair? Leave as is? Esp. since our decision on #47 will likely change variables we allow NSE for to no longer end in "_name"

**Comment by graemeblair** [comment]
@lukesonnet will come back to you by Friday so until then we can leave as is

**Comment by lukesonnet** [comment]
Will close this by Friday and leave behavior as is unless told otherwise.

**Comment by graemeblair** [comment]
thx, closing this and moving to a broader issue about NSE https://github.com/DeclareDesign/DeclareDesign/issues/61
