### ISSUE TITLE
Error in Travis-CI when building vignettes

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#51]
Because this vignette will have a lot of math, I think it's best to build it as a PDF unless there are objections. If there are, perhaps we can discuss them in #10.

However, because it is a PDF, it is built using LaTeX and there is an error in the Mac set-up on Travis-CI (seen [here](https://travis-ci.org/DeclareDesign/estimatr/jobs/297265522)) where we basically only need to add texlive-extras to the install unless there are other suggestions.

However, we don't currently use a .travis.yml so I'm not sure where these settings exist. @graemeblair?

**Comment by graemeblair** [comment]
They're in .travis.yml in `estimatr` (we do use this). Neal is working on a docker replacement for how we're using travis right now, so I think if you are good to stick with your solution for the meantime that would avoid figuring out these issues.

**Comment by lukesonnet** [comment]
Sorry, still figuring out why my Mac sometimes shows hidden files and why other times it does not. I'll close this for now and we can revisit these bugs post nfultz.

**Comment by aaronrudkin** [comment]
Did we ever get a solution on this? I tried to add a few short equations to the documentation of a couple functions in fabricatr and ran into a bunch of complaining from travis. They're not crucial to functionality, but I'd like it so that when I look at the code a year from now I remember what goes on in the math.
