### ISSUE TITLE
Travis-CI build error downloading BasicTex

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#6]
I'm getting a build error caused by a 403 error to download BasicTex.

Build log: https://travis-ci.org/DeclareDesign/estimatr/jobs/262133520

Any ideas would be helpful, but I'll just leave this here until I can find a solution.

**Comment by graemeblair** [comment]
Thanks, Luke. This issue has been coming up frequently and is a general issue not specific to ours.

With Aaron's help I've posted a PR to travis to retry it until the download works; it's been accepted I think and should update in the next week or two I think.

I'm going to close this because I'm tracking that update. Feel free to ping me if you want me to restart a build or ignore for now. Note it's usually just the OS X old release of R that breaks.
