### ISSUE TITLE
warning in windows on package load

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/estimatr#61]
Macartan is getting this warning when he loads `estimatr` on windows even after a full, clean reinstall of all the packages via github:

## available when loading

This may be windows specific; I haven't seen it on mac.

**Comment by lukesonnet** [comment]
Hmmm, this seems to only be a warning when running packages in parallel. Is he just loading it in a plain R session/Rstudio?

**Comment by graemeblair** [comment]
@macartan when do you see this error, when you do

`library(estimatr)`

or something more complex?

**Comment by macartan** [comment]
When I diagnose. I can load and use estimatr. M

On Nov 27, 2017 5:04 PM, "Graeme Blair" <notifications@github.com> wrote:

@macartan <https://github.com/macartan> when do you see this error, when
you do

library(estimatr)

or something more complex?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/DeclareDesign/estimatr/issues/61#issuecomment-347229561>,
or mute the thread

**Comment by nfultz** [comment]
This might be an import or namespace problem in declaredesign.

**Comment by lukesonnet** [comment]
Yes I believe this is a DeclareDesign issue. I believe the problem is with the namespace in the instances created by `parallel`.

Who is most familiar with that code?

**Comment by graemeblair** [comment]
moved to https://github.com/DeclareDesign/DeclareDesign/issues/64
