### ISSUE TITLE
Make output stargazable

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#7]
While possibly keeping the output as a dataframe, try to make it so that it can be easily passed to stargazer.

**Comment by graemeblair** [comment]
Ok, so here's a solution: add an option to `lm_robust_se` called `return_model_fit` or similar that defaults to FALSE, which means it returns a `data.frame` as it does now. When set to true, it returns an object that mimics an `lm` fit object, which then stargazer can use.

**Comment by acoppock** [comment]
I think this will be hard, because the `lm` fit object doesn't actually appear to have an estimated vcov matrix. It must be that stargazer calls `vcov` or similar.  Might be worth a little bit of investigation, but it wasn't immediately obvious to me how to do it.  I also couldn't find some kind of generic stargazer model object type, but maybe i missed it.

**Comment by lukesonnet** [comment]
Not supporting stargazer for now. Will focus on other packages as per #74.
