### ISSUE TITLE
Allow input to be a model fit

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#8]
Argument for clusters should take a vector of the same length as the data in the model matrix.

We should split the lm_robust function in to:
* Two functions, both called lm_robust. A generic function that prepares the model matrix and such and a function that recognizes a model fit.
* A function that takes the result of the above functions, does all fitting + inference as necessary and returns our usual output

**Comment by graemeblair** [comment]
Sounds good! 

This may be what you mean, but on clusters, it should take the bare, unquoted name of the variable and extract it itself inside the function from the data that's also an argument -- not take a vector -- to be consistent with the other functions.

**Comment by lukesonnet** [comment]
That's actually not what I meant, because of what we discussed last night. The problem arises because if you have some data frame that you pass to our function along with the model fit object, you may pass data that is of a different length from the model.matrix in the model fit object if there was listwise deletion. Then you have to figure out a way to subset the appropriate elements from the column that has the weights.

However, we can keep it consistent as you suggest if we error if the dataframe they pass us is of different length than the model matrix in the model fit object. Is this what you would prefer?

**Comment by graemeblair** [comment]
Yeah, I don't the right solution is to accept a vector since that would be a very different behavior (and would introduce additional problems with list-wise deletion).

We'd want to error anyway if the df's were of different dimension, so keeping it consistent and erroring as you suggest sounds right to me.

**Comment by lukesonnet** [comment]
Sounds good. Also could add use_rownames to allow diff lengths but use rownames to match? Default to false?

**Comment by graemeblair** [comment]
That sounds good to me, though confess I'm not sure what dragons across all ways a user might send things to us (i.e. row names happen to agree). Default to false might avoid at least most problems.

**Comment by acoppock** [comment]
I think I only want to do this 2 ways:

1) you do

lm_robust(Y~Z, cluster_variable = clust, data = df)

or

2)

lm_robust(model_fit, cluster_variable = df$clust)

which *only* uses the length and not the row names (which seems super duper
error prone).


Am not sure that the two functions should have same name.


On August 9, 2017 at 9:30:40 AM, Graeme Blair (notifications@github.com)
wrote:

That sounds good to me, though confess I'm not sure what dragons across all
ways a user might send things to us (i.e. row names happen to agree).
Default to false might avoid at least most problems.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DeclareDesign/estimatr/issues/8#issuecomment-321255634>,
or mute the thread

**Comment by graemeblair** [comment]
Okay. I think for DeclareDesign purposes we don't need any function that takes a model fit object. Alex and I agree we shouldn't create an extra function that will only be used by `commarobust`. So let's leave it at lm_robust and not accept model fits. Alex will rely on the Rcpp code directly for `commarobust'.
